site_name: "TeskaLabs SeaCat Auth"
theme:
  name: 'material'

  font:
    text: Verdana

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.indexes

  logo: images/teskalabs-logo.svg

  favicon: images/teskalabs.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: True
      separator: "-"
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TeskaLabs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/teskalabs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teskalabs
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@teskalabs.com
      name: info@teskalabs.com

nav:
  - About:
    - index.md
    - reference/features.md


  - Administration guide:
    - admin/index.md
    - Installation:
      - installation/quick-start.md
      - installation/provisioning.md

    - Configuration:
      - config/basic-configuration.md
      - Credentials:
        - config/credentials/index.md
        - config/credentials/credentials-policy.md
        - config/credentials/providers.md
      - Authentication and login:
        - config/external-login.md
      - config/notifications-configuration.md
  
    - Integrating apps:
      - integrations/index.md
      - integrations/oauth2-introspect.md
      - Connecting other apps:
        - integrations/cookies.md
        - integrations/elk.md     
        - integrations/the-hive.md
  
    - Development:
      - REST API:
        - development/rest-api.md
        - development/postman.md
      - development/oauth2.md
  
    - Reference:
      - reference/architecture.md
      - reference/components.md
      - reference/resources.md
      - reference/clients.md
      - reference/session.md


  - User guide (UI):
      - user/index.md
      - user/key-terms.md
      - user/login.md
      - user/credentials.md
      - user/tenants.md
      - user/resources.md      
      - user/roles.md
      - user/clients.md
      - user/sessions.md