site_name: "TeskaLabs documentation"
theme:
  name: 'material'

  font:
    text: Verdana

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: images/teskalabs-logo.svg

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: True
      separator: "-"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TeskaLabs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/teskalabs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teskalabs
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@teskalabs.com
      name: info@teskalabs.com
