site_name: "TeskaLabs SeaCat Auth"
theme:
  name: 'material'

  font:
    text: Verdana

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: images/teskalabs-logo.svg

  favicon: images/teskalabs.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: True
      separator: "-"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TeskaLabs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/teskalabs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teskalabs
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@teskalabs.com
      name: info@teskalabs.com

nav:
  - index.md

  - Getting started:
    - getting-started/quick-start.md
    - getting-started/recommended-deployment.md
    - config/provisioning.md

  - Configuration:
    - config/basic-configuration.md
    - config/docker.md
    - config/cookies.md
    - config/external-login.md
    - config/ldap.md
    - config/oauth2-introspect.md
    - config/mail.server.md
    - config/bouncer.md
    - Credentials:
      - config/credentials/index.md
      - config/credentials/credentials-policy.md
      - config/credentials/providers.md

  - Integrations:
    - integrations/index.md
    - integrations/elk.md
    - integrations/the-hive.md
  
  - Development:
    - development/rest-api.md
    - development/oauth2.md
    - development/postman.md
    - development/unit-test.md

  - Reference:
    - features/features.md
    - reference/architecture.md
    - reference/rbac.md
    - reference/resources.md
    
  - User guide (UI):
    - webui/key-terms.md
    - webui/seacat-auth-web-ui.md