import datetime
import logging
import secrets

import asab

#

L = logging.getLogger(__name__)

#


class RegistrationService(asab.Service):

	RegistrationTokenCollection = "rg"
	RegistrationTokenByteLength = 32
	RegistrationKeyByteLength = 32
	RegistrationUriFormat = "{auth_webui_base_url}#register?token={token_id}"

	def __init__(self, app, cred_service, service_name="seacatauth.RegistrationService"):
		super().__init__(app, service_name)
		self.CredentialsService = cred_service
		self.CommunicationService = app.get_service("seacatauth.CommunicationService")
		self.AuditService = app.get_service("seacatauth.AuditService")
		self.StorageService = app.get_service("asab.StorageService")

		self.AuthWebUIBaseUrl = asab.Config.get("general", "auth_webui_base_url").rstrip("/")

		self.InviteExpiration = asab.Config.getseconds("seacatauth:registration", "expiration", fallback=0)

		self.RegistrationEncrypted = asab.Config.getboolean("seacatauth:registration", "registration_encrypted")
		if self.RegistrationEncrypted:
			raise NotImplementedError("Registration encryption has not been implemented yet.")

		self.SelfRegistrationAllowed = asab.Config.getboolean("seacatauth:registration", "allow_self_registration")
		if self.SelfRegistrationAllowed:
			raise NotImplementedError("Self-registration has not been implemented yet.")


		self.App.PubSub.subscribe("Application.tick/60!", self._on_tick)


	async def _on_tick(self, event_name):
		await self.delete_expired_registration_tokens()


	async def create_registration_token(
		self,
		expiration: float,
		credential_data: dict = None,
		invited_by_cid: str = None,
		invited_by_ips: list = None,
	):
		"""
		Issue a new registration token

		:param credential_data: Details of the user being registered
		:type credential_data: dict
		:param expiration: Number of seconds specifying the expiration of the token
		:type expiration: float
		:param invited_by_cid: Credentials ID of the issuer.
		:type invited_by_cid: str
		:param invited_by_ips: IP address(es) of the issuer.
		:type invited_by_ips: list
		:return: The generated registration token.
		"""
		token_id = secrets.token_urlsafe(self.RegistrationTokenByteLength)
		upsertor = self.StorageService.upsertor(self.RegistrationTokenCollection, token_id)

		key = secrets.token_bytes(self.RegistrationKeyByteLength)
		upsertor.set("__k", key, encrypt=True)

		# TODO: The credential_data should be in line with the registration policy
		# policy = self.CredentialsService.Policy.RegistrationPolicy
		upsertor.set("c", credential_data)

		if invited_by_cid is not None:
			upsertor.set("ic", invited_by_cid)

		if invited_by_ips is not None:
			upsertor.set("ii", invited_by_ips)

		expires_at = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(seconds=expiration)
		upsertor.set("exp", expires_at)

		await upsertor.execute(custom_data={"event_type": "registration_token_created"})

		L.log(asab.LOG_NOTICE, "Registration token created", struct_data={
			"token_id": token_id,
			"invited_by_cid": invited_by_cid,
			"invited_by_ips": invited_by_ips,
		})

		return token_id


	async def set_registration_token_key(self, token_id, **kwargs):
		"""
		Generate a random key, encrypt it, and store it in the token object in the database.

		:param token_id: The ID of the token to set the key for
		:return: The generated key.
		"""
		token = await self.get_registration_token(token_id)
		upsertor = self.StorageService.upsertor(
			self.RegistrationTokenCollection,
			obj_id=token_id,
			version=token["_v"])
		key = secrets.token_bytes(self.RegistrationKeyByteLength)
		upsertor.set("__k", key, encrypt=True)
		return key


	async def update_registration_token(self, token_id, **kwargs):
		# TODO
		raise NotImplementedError()


	async def get_registration_token(self, token_id):
		"""
		Retrieve registration token from the database. If it's expired, raise KeyError.

		:param token_id: The token ID
		:return: Token data.
		"""
		token = await self.StorageService.get(self.RegistrationTokenCollection, token_id, decrypt=["__k"])
		if token["exp"] < datetime.datetime.now(datetime.timezone.utc):
			raise KeyError("Expired token")
		return token


	async def delete_registration_token(self, token_id):
		"""
		Delete a registration token from the database

		:param token_id: The token generated by the registration service
		"""
		await self.StorageService.delete(self.RegistrationTokenCollection, token_id)
		L.log(asab.LOG_NOTICE, "Registration token deleted", struct_data={"token_id": token_id})


	async def delete_expired_registration_tokens(self):
		"""
		Delete all registration tokens that have expired
		"""
		collection = self.StorageService.Database[self.RegistrationTokenCollection]
		query_filter = {"exp": {"$lt": datetime.datetime.now(datetime.timezone.utc)}}
		result = await collection.delete_many(query_filter)
		if result.deleted_count > 0:
			L.log(asab.LOG_NOTICE, "Expired registration tokens deleted", struct_data={
				"count": result.deleted_count})


	def get_provider(self, provider_id: str = None):
		"""
		Locate a provider that supports credentials registration

		:param provider_id: The ID of the provider to use. If not specified, the first
		provider that supports registration will be used
		:type provider_id: str
		:return: A provider object
		"""
		# Specific provider requested
		if provider_id is not None:
			provider = self.CredentialsService.Providers.get(provider_id)
			if provider.Config.getboolean("registration"):
				return provider
			else:
				L.warning("Provider does not support registration", struct_data={"provider_id": provider_id})
				return None

		# No specific provider requested; get the first one that supports registration
		for provider in self.CredentialsService.CredentialProviders.values():
			if provider.Config.getboolean("registration"):
				return provider
		else:
			L.warning("No credentials provider with enabled registration found")
			return None


	async def create_invitation(
		self,
		tenant: str,
		email: str,
		roles: list = None,
		provider_id: str = None,
		expiration: float = None,
		invited_by_cid: str = None,
		invited_by_ips: str = None,
	):
		"""
		Create an invitation into a tenant and send it to a specified email address.

		:param tenant: The tenant to which the user will be invited
		:type tenant: str
		:param email: The email address of the user to invite
		:type email: str
		:param roles: List of roles to be assigned to the registered user
		:type roles: list
		:param provider_id: The ID of the provider that will be used for registration
		:type provider_id: str
		:param expiration: The expiration time of the token in seconds
		:type expiration: float
		:param invited_by_cid: The credential ID of the user who issued the invitation
		:type invited_by_cid: str
		:param invited_by_ips: The IP addresses of the user who issued the invitation
		:type invited_by_ips: str
		:return: The ID of the generated token.
		"""

		if expiration is None:
			expiration = self.InviteExpiration

		credential_data = {
			"provider_id": provider_id,
			"email": email,
			"tenant": tenant,
			"roles": roles,
		}

		# TODO: Validate credential data:
		#   - provider_id exists and supports registration
		#   - tenant exists
		#   - roles exist and match tenant

		token_id = await self.create_registration_token(
			expiration,
			credential_data=credential_data,
			invited_by_cid=invited_by_cid,
			invited_by_ips=invited_by_ips,
		)

		# TODO: Send invitation via mail
		# await self.CommunicationService.registration_link(email=email, registration_uri=registration_uri)
		L.log(asab.LOG_NOTICE, "Sending invitation", struct_data={
			"email": email,
			"t": tenant,
			"r": roles,
			"issued_by_cid": invited_by_cid,
			"issued_by_ips": invited_by_ips,
			"registration_token": token_id,
			"registration_uri": self.format_registration_uri(token_id),
		})

		return token_id


	async def register_credentials(self, register_info: dict):
		"""
		This is an anonymous user request to register (create) new credentials
		"""
		provider = self.get_provider()
		if provider is None:
			return None
		return await provider.register(register_info)


	def format_registration_uri(self, token_id: str):
		return self.RegistrationUriFormat.format(
			auth_webui_base_url=self.AuthWebUIBaseUrl,
			token_id=token_id)
