version: '3'
services:

  # Database for SeaCat Auth
  mongo:
    image: mongo
    volumes:
      - /data/mongodb:/data/db
      - ./log:/log
    network_mode: host

  # Nginx reverse-proxy
  nginx:
    image: nginx
    depends_on:
      - seacat-auth
    network_mode: host
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./log:/log
      - ./seacat-auth-webui:/seacat-auth-webui
      - ./seacat-webui:/seacat-webui

  # SeaCat Auth microservice
  seacat-auth:
    environment:
      # Provisioning mode switch (Set to 1 or TRUE to activate provisioning mode)
      - SEACAT_AUTH_PROVISIONING=0
    image: teskalabs/seacat-auth:latest
    # build:
    #   context: ../..
    #   dockerfile: Dockerfile
    depends_on:
      - mongo
    network_mode: host
    volumes:
      - ./seacatauth-conf:/conf
      - ./log:/log
