version: '3'
services:

  # Database for SeaCat Auth
  mongo:
    image: mongo
    volumes:
      - ./mongo-data/mongodb:/data/db
      - ./log/mongo:/log
    network_mode: host

  # Nginx Web Server configured as a reverse proxy
  nginx:
    image: nginx
    depends_on:
      - seacat-auth
    network_mode: host
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./log/nginx:/log
      - ./seacat-auth-webui:/seacat-auth-webui
      - ./seacat-webui:/seacat-webui

  # SeaCat Auth
  seacat-auth:
    environment:
      # Provisioning mode switch (Set to 1 or TRUE to activate provisioning mode)
      - SEACAT_AUTH_PROVISIONING=1
    image: teskalabs/seacat-auth
    depends_on:
      - mongo
    network_mode: host
    volumes:
      - ./seacatauth-conf:/conf
      - ./log/seacatauth:/log

  # Demo application
  demo-app:
    build:
      context: ./demo-app
      dockerfile: Dockerfile
    depends_on:
      - seacat-auth
    network_mode: host
    volumes:
      - ./demo-app/demoapp.conf:/conf/demoapp.conf
