name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install git+https://github.com/TeskaLabs/asab.git
    
    - name: Lint with flake8
      run: |
        flake8 seacatauth seacatauth.py
  
  test:
    needs: flake8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bson
        pip install pymongo
        pip install bcrypt
        pip install argon2
        pip install jwcrypto
        pip install git+https://github.com/TeskaLabs/asab.git#egg=asab[encryption]
    
    - name: Test with unittest
      run: |
        python3 -m unittest test

  build:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Metadata action
      uses: docker/metadata-action@v5
      id: meta
      with:
          images:  teskalabs/seacat-auth
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=semver,pattern={{raw}}
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }} 
        password: ${{ secrets.DOCKER_PASSWORD }}  
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Create Docker Starter
      uses: vimtor/action-zip@v1.2
      with:
        files: example/docker
        dest: seacat-auth-docker-starter.zip

    - name: Upload Docker Starter
      uses: actions/upload-artifact@v4
      with:
        name: seacat-auth-docker-starter
        path: ${{ github.workspace }}/seacat-auth-docker-starter.zip
